-- MySQL Script generated by MySQL Workbench
-- 01/30/18 10:43:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qsx_resume
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qsx_resume
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qsx_resume` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `qsx_resume` ;

-- -----------------------------------------------------
-- Table `qsx_resume`.`t_education_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_education_degree` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_working_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_working_status` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_about_me`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_about_me` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `birthday` DATE NOT NULL,
  `motto` VARCHAR(500) NULL DEFAULT '',
  `residence` VARCHAR(255) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `mobile` VARCHAR(50) NOT NULL DEFAULT '',
  `workingYears` VARCHAR(50) NOT NULL,
  `education_degree_id` BIGINT(20) NOT NULL,
  `working_status_id` BIGINT(20) NOT NULL,
  `resumeFile` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aboutme_edudegree_idx` (`education_degree_id` ASC),
  INDEX `fk_aboutme_workstatus_idx` (`working_status_id` ASC),
  CONSTRAINT `fk_aboutme_edudegree`
    FOREIGN KEY (`education_degree_id`)
    REFERENCES `qsx_resume`.`t_education_degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aboutme_workstatus`
    FOREIGN KEY (`working_status_id`)
    REFERENCES `qsx_resume`.`t_working_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_contact` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_education` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `period` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `brief` VARCHAR(500) NOT NULL DEFAULT '',
  `indexNo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_experience` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `period` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `brief` VARCHAR(500) NOT NULL DEFAULT '',
  `indexNo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_hobby` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `indexNo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_honor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_honor` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `brief` VARCHAR(500) NOT NULL,
  `indexNo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `qsx_resume`.`t_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qsx_resume`.`t_skill` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `level` INT(11) NOT NULL,
  `indexNo` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
